#debug: true
spring:
  h2:
    console:
      enabled: true
      path: /h2
  resources:
    static-location: /images
  datasource:
    platform: h2
    url: jdbc:h2:file:./storage;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    username: sa
    password:
    driver-class-name: org.h2.Driver
    schema: /sql/h2-schema.sql
#    data: /sql/h2-data.sql
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: update
      properties.hibernate.dialect: org.hibernate.dialect.H2Dialect